Batch video processing cycle
FIT-2023-SLAM-indoor/slam-indoor-code pull request #25
Opened 2023-11-19 10:44 UTC by IgorShal

In factr,it's not ready yet, i haven't added taking best frame from pool function in case of all bad. Cause i have some problem in that case. I'd like to talk with Kirill about this one. But we can use it.

2023-11-21 09:05 UTC, KozlovKV requested changes

2023-11-21 09:05 UTC, KozlovKV commented on src/videoProcessingCycle.cpp
> +		if (countOfFrames <= framesBatchSize) {
Может быть нам здесь дополинтельно экстрактить фичи исключительно для проверки замазанности изображения (исходим из предположения, что на заблюрренных кадрах фич будет очень мало). Не уверен, что эта идея хорошая, надо тестировать

2023-11-21 09:05 UTC, KozlovKV commented on src/videoProcessingCycle.cpp
> +		if (countOfFrames <= framesBatchSize) {
Вместо отдельного счётчика вроде как можно использовать метод вектора для получения его размера. Тогда можно будет избавиться от строки ещё и в конце главного цикла + мы сможем гарантировать, что у нас ровно столько кадров, сколько надо в батче

2023-11-21 09:05 UTC, KozlovKV commented on src/videoProcessingCycle.cpp
> +				newBatch.push_back(currentFrame);
Не подошедшие кадры мы добавляем в новый батч, но добавляем их в обратном порядке. Надо либо использовать здесь метод `insert`, для добавления в голову вектора нового кадра, либо в конце испозовать `reverse` (это не метод вектора, а более замысловатая штука).
Также есть вариант, о котором я говорил на паре: считать за аксимому не слишком большие размеры батчей => мы не упадём в яму пропусков => можно обнулять текущий батч, если нашли удачный кадр, а дальше просто строить новый

2023-11-21 09:05 UTC, KozlovKV commented on src/videoProcessingCycle.cpp
> +		batch = newBatch;
Смотри коммент про формирование нвого батча выше

2023-11-21 09:05 UTC, KozlovKV commented on src/videoProcessingCycle.cpp
> +
Насчёт действия при ненахождении ни одного нормального кадра в батче: думаю, выбирать максимально хороший из плохих - такое себе. Придётся искать ещё и константу строго минимально допустимого количества точек, и что-нибудь ещё наверняка всплывёт. Пока что оптимальным вариантом выглядит сбросить на дэфолтное значение `previousProjectionMatrix` (другие матрицы не трогать!), поставить флаг `first` в `true` и завершить итерацию while'а - мы просто примем как данность, что приемтсенность ~поколений~ кадров разрушена и начнём строить новую цепочку, притворившись, что сдвига от последнего нормального распознования не было вовсе

2023-11-21 12:31 UTC, KozlovKV commented on src/videoProcessingCycle.cpp
> +				newBatch.push_back(currentFrame);
Ещё один резон для сбрасывания батча при нахождении кадра: есть вероятность, что кадры были пропущены потому, что они плохие сами по себе (пресловутый блюр и т.п.), поэтому забивать ими следующий батч = повышать вероятность не нахождения в нём подходящих кадров. Как альтернативный вариант, можно добавлять их в следующий батч, но загружать в него дополнительно всегда заданное количество кадров, то есть мы будем получать расширенные батчи (да-да, тогда замечание про запрос длины у вектора перестаёт быть актуальным)

2023-11-21 12:35 UTC, KozlovKV commented on src/videoProcessingCycle.cpp
> +				newBatch.push_back(currentFrame);
В общем, накидал я много вариантов, так что постараюсь подвести тут краткий итог:
1. Можно сбрасывать батч при нахождении нормального кадра и просто заполнять следующий. Скорее всего, будет работать достаточно стабильно при правильном подборе размера батча
2. Если закидывать не прошедшие проверку кадры, то:
   - Надо закидывать их с учётом порядка (в голову нового батча либо инвертировать его в конце цикла)
   - Желательно догружать в батч всё равно `framesBatchSize` новых кадров

2023-11-21 14:06 UTC, IgorShal commented on src/videoProcessingCycle.cpp
> +		if (countOfFrames <= framesBatchSize) {
Зач

2023-11-21 14:08 UTC, IgorShal commented on src/videoProcessingCycle.cpp
> +		if (countOfFrames <= framesBatchSize) {
Как будто вектор медленнее счетчика, но, скорее всего, они тоже счётчик в векторе юзают, поэтому согласен

2023-11-21 14:14 UTC, IgorShal commented on src/videoProcessingCycle.cpp
> +				newBatch.push_back(currentFrame);
Вообще, основной смысл текущей реализации батчей это отсутствие пропусков кадров. Непрерывные переходы. Если же нам нестрашно, что мы несколько кадров теряем, то ладно

2023-11-21 14:17 UTC, IgorShal commented on src/videoProcessingCycle.cpp
> +				newBatch.push_back(currentFrame);
То есть первый вариант - мы просто забиваем на пропущенные кадры и строим новый батч без них?

2023-11-21 14:20 UTC, IgorShal commented on src/videoProcessingCycle.cpp
> +
Примерно так и было в предыдущей версии цикла с фрейм гепами. Но мы вроде отказались от этого костыля. Возможно я не очень хорошо объяснил, зачем он нужен был

2023-11-21 16:49 UTC, KozlovKV commented on src/videoProcessingCycle.cpp
> +		if (countOfFrames <= framesBatchSize) {
Для оптимизации, причём возможно весьма ощутимой. Но это вопрос дискуссионный и не к спеху

2023-11-21 16:50 UTC, KozlovKV commented on src/videoProcessingCycle.cpp
> +		if (countOfFrames <= framesBatchSize) {
Кстати, не факт - вроде когда как-то с Галей беседовал, она говорила, что он там втупую считает. Так что отсавляем так

2023-11-21 16:51 UTC, KozlovKV commented on src/videoProcessingCycle.cpp
> +				newBatch.push_back(currentFrame);
Думаю, потеря кадров, которые уже были один раз посчитаны плохими (а значит и вероятность посчитать их такими повторно высока) - это не проблема

2023-11-21 16:51 UTC, KozlovKV commented on src/videoProcessingCycle.cpp
> +				newBatch.push_back(currentFrame);
Да, в первом варианте мы на них просто забиваем

2023-11-21 16:52 UTC, KozlovKV commented on src/videoProcessingCycle.cpp
> +
А почему это костыль? Будто бы выбирать не особо хороший кадр - это решение не лучше, чем отказаться от них вовсе. Ладно, обсудим завтра

2023-11-25 15:47 UTC, KozlovKV approved these changes
Всё супер! Осталось внести одну минорную правку

2023-11-25 15:53 UTC, KozlovKV approved these changes

2023-11-25 15:53 UTC, KozlovKV commented on src/videoProcessingCycle.cpp
>  		cap.read(currentFrame);
Добавь проверку на считывание пустого кадра. Если это произошло, то выходим из основного цикла (а то не очень хорошо там бесконечно сидеть да и потоки файлов надо закрывать, а сейчас их строчки недостижимы)

2023-11-25 15:53 UTC, KozlovKV commented on src/videoProcessingCycle.cpp
> +		countOfFrames = newBatch.size();
Этот блок было бы логичнее сдвинуть вниз под закомментированную часть, так как он также, как и строчки там, отвечает за передачу данных в переменные/файлы при завершении итерации

2023-11-25 15:53 UTC, KozlovKV commented on src/videoProcessingCycle.cpp
> +		/* This code shows tracked points
Сам блок будто бы лучше не комментировать, а засунуть в `#ifdef` либо и вовсе в `if`

2023-11-25 15:53 UTC, KozlovKV commented on src/videoProcessingCycle.h
> + * @return 0 if everything is ok, -1 otherwise.
А когда у нас возврат `-1` может произойти?

2023-11-25 16:31 UTC, IgorShal commented on src/videoProcessingCycle.h
> + * @return 0 if everything is ok, -1 otherwise.
согласен, нигде

2023-11-25 18:20 UTC, merged