Visualizer
FIT-2023-SLAM-indoor/slam-indoor-code pull request #28
Opened 2023-11-29 01:59 UTC by AntonTsoy

2023-11-29 02:16 UTC, IgorShal commented on python_utility/visualize.py
> +    if keys.get(p.B3G_RIGHT_ARROW):  # >
Сомнительно, но окэй

2023-11-29 02:16 UTC, IgorShal commented on python_utility/visualize.py
> +    if keys.get(p.B3G_RIGHT_ARROW):  # >
А чё щас можно двигаться, пока карта создаётся или нет?

2023-11-29 02:16 UTC, IgorShal commented on python_utility/visualize.py
> +    if keys.get(p.B3G_RIGHT_ARROW):  # >
По коду можно, а по факту?

2023-11-29 02:20 UTC, AntonTsoy commented on python_utility/visualize.py
> +    if keys.get(p.B3G_RIGHT_ARROW):  # >
я тестировал у себя и у меня работало. Но максимум, на котором я запускал - 1500 точек. На большем количестве, наверное могут начаться проблемы. Но это уже ограничения PyBullet и устройства, на котором работает прога. В будущем можно постараться оптимизировать код

2023-11-29 02:21 UTC, IgorShal commented on python_utility/visualize.py
> +    if keys.get(p.B3G_RIGHT_ARROW):  # >
Отлично, очень рад, что можно двигаться, пока карта строится!

2023-11-29 02:33 UTC, KozlovKV commented
`venv` может именоваться сильно по разному, а кто-то, возможно, будет использовать даже не его, так что лучше добавить все записи по ключу `python` (и возможно каким-то ещё) с этого сайта - https://www.toptal.com/developers/gitignore

2023-11-29 02:47 UTC, KozlovKV requested changes
Пока что не всё сверх подробно глянул. Возможно потому напишу что-то ещё

2023-11-29 02:47 UTC, KozlovKV commented on .gitignore
> +.venv
`venv` может именоваться сильно по разному, а кто-то, возможно, будет использовать даже не его, так что лучше добавить все записи по ключу `python` (и возможно каким-то ещё) с этого сайта - https://www.toptal.com/developers/gitignore

2023-11-29 02:47 UTC, KozlovKV commented on python_utility/visualize.py
> +stadium = p.loadSDF("stadium.sdf")
А давай всё же плоскость из квадратиков? XD

2023-11-29 02:48 UTC, KozlovKV commented on python_utility/visualize.py
> +stadium = p.loadSDF("stadium.sdf")
Хотя это вопрос обсуждаемый

2023-11-29 02:51 UTC, IgorShal commented
Предложение: добавить пару клавиш для регулирования скорости движения.

2023-11-29 02:51 UTC, IgorShal approved these changes

2023-11-29 03:21 UTC, KozlovKV requested changes
Предлагаю следующую схему управления, как у самолёта (все движения относительно текущего положения):
- `S`/`X` - вперёд/назад
- `Z`/`C` - поворот влево/вправо
- Стрелка влево / стрелка вправо - крен влево/вправо
- Стрелка вверх/вниз - подъём "носа" вверх / вниз (инвертированный тангаж) 
- * `Shift`/`Ctrl` - повышение/понижение скорости
- * `Q`/`A` - пусть также отвечают за высоту

Очень вероятно, при такой реализации будет лучше, если вращение будет происходить относительно точки камеры

2023-11-29 03:21 UTC, KozlovKV commented on python_utility/visualize.py
> +points_data = open("../data/video_report/test.txt",'r')
Перенести путь к файлу с точками в конфиг файл, который будет добавлен в `.gitignore`, чтобы мы могли менять файлы для генерации у себя и не менять отслеживаемые гитом файлы

2023-11-29 03:21 UTC, KozlovKV commented on python_utility/visualize.py
> +            points_data.close()
Добавить вывод сообщения об окончании файла. Пока что последняя строка будет обозначаться словом `FINISH`

2023-11-29 03:21 UTC, KozlovKV commented on python_utility/visualize.py
> +    startPos = [float(res[0]),float(res[1]),float(res[2])]
Дополнительно проверять размерность массива полученных строчек с числами (можно отлавливать исключение - тут на твоё усмотрение)

2023-11-29 07:22 UTC, AntonTsoy commented on python_utility/visualize.py
> +stadium = p.loadSDF("stadium.sdf")
это я просто по приколу поставил, сам по себе PR сделал, чтобы обратную связь получить. Говорите, что хотите поставить, я поставлю. Можно вообще не делать плоскость

2023-11-29 08:26 UTC, KozlovKV commented on python_utility/visualize.py
> +stadium = p.loadSDF("stadium.sdf")
Не, плоскость какую-то лучше поставить, будет проще оринтироваться. Идеальный вариант - бесконечная из квадртаиков (вроде такая и была изначально)

2023-11-29 15:42 UTC, AntonTsoy commented on .gitignore
> +.venv
я не разобрался, как пользоваться этим ресурсом, пока решение простое. Я игнорирую не ```.venv```, а ее содержимое

2023-11-30 02:43 UTC, KozlovKV requested changes

2023-11-30 02:43 UTC, KozlovKV commented on .gitignore
> +.venv
Вводишь в поискую строку ключевые слова, связанные с языком, IDE и какими-либо ещё штуками (тут хватит ключей `python` и, допустим `pycharm` и `vs code` (последний ключ не точный, но что-то похожее должно быть)), нажимаешь сгенерировать и копируешь весь полученный текст в `.gitignore` (ясное дело, не перезаписывая то, что там уже есть)

2023-11-30 02:55 UTC, AntonTsoy commented on .gitignore
> +.venv
Готово, кэп

2023-11-30 03:14 UTC, AntonTsoy commented
Добавить растягивание точек по оси Z

2023-12-01 18:19 UTC, KozlovKV requested changes
Ну и безотносительно кусков кода 2 момента:
1. Имеет смысл добавить точку входа `if __name__ == '__main__:`
2. Выглядит так, будто код неплохо упаковывается в класс: инициализацию `pybullet` запихать в конструктор, а остальные функции сделать методами этого класса. В `main` (либо самой точке входа) тогда останется создание объекта и вызов его метода типа `mainVisualizationCycle`

2023-12-01 18:19 UTC, KozlovKV commented on python_utility/visualize.py
> +COORD_Z_SCALE = 7.0
Главное, не забудь реализовать этот скейлинг. А сам параметр можно бы перенести в `config.py`

2023-12-01 18:19 UTC, KozlovKV commented on python_utility/README.md
> +# Бета версия (27.11.2023)
Добавь в начале блок с описанием переменных из конфига

2023-12-01 18:19 UTC, KozlovKV commented on python_utility/visualize.py
> +def visible(line):
Как мне кажется, имеет смысл переименовать во что-то типа `visualizePointFromString`, так как в делающих какое-то действие функциях очень желателен глагол

2023-12-01 18:19 UTC, KozlovKV commented on python_utility/visualize.py
> +coeff = 0.115
Хотелось бы поменьше коротких имён либо пояснения к ним в виде комментариев, иначе разбираться немного сложно

2023-12-01 18:19 UTC, KozlovKV commented on python_utility/README.md
> +[w] - особенный режим просмотра объектов <br>
Вообще, в markdown можно делать списки чуть элегантнее (хотя может ты тут хотел именно такой вид, так что это просто фан-факт): начиать кажду строчку с `- `

2023-12-01 18:19 UTC, KozlovKV commented on python_utility/visualize.py
> +
Функционал цикла вроде как чётко делится на 2 подзадачи, для которых можно сделать 2 функции:
1. Отрисовать прочтённую точку
2. Считатать нажатие клавиши и поменять в зависимости от него положение

2023-12-05 03:05 UTC, merged