Added Open3D point cloud visualizer
FIT-2023-SLAM-indoor/slam-indoor-code pull request #34
Opened 2024-02-19 15:17 UTC by AntonTsoy

2024-02-19 15:22 UTC, AntonTsoy commented
Пример config.py
`VIZ_FILE_PATH = "../data/points.txt"
VIZ_PARSE_FORMAT = "xyz"`

2024-02-19 15:30 UTC, AntonTsoy commented
Если указывать относительный путь, как в примере выше, то могут возникнуть проблемы при исполнении кода. У меня не получалось нормально сынтерпретировать его в VS Code. Пришлось при АКТИВИРОВАННОЙ виртуальной среде исполнять: `(.venv) \ПОЛНЫЙ_ПУТЬ\> python visualizer.py`

2024-02-19 15:32 UTC, AntonTsoy commented
Формат содержания points.txt файла:
```CMake
# X Y Z
0 2 0
3 -1 3
3 -1 -3
-3 -1 3
-3 -1 -3
-2 0 -2
-2 0 1.95
1.873 0.012 2.12
```

2024-02-20 02:11 UTC, KozlovKV requested changes

2024-02-20 02:11 UTC, KozlovKV commented on .gitignore
> +data/
Игнорировать папку data полностью всё же не стоит, я думаю. Теоретически, мы можем туда поместить какой-то файл, который хотим всем передать. Другой вариант - создать другую папку вроде `static` и в неё кидать то, чем хотим поделиться. Какой нравится больше?

2024-02-20 02:13 UTC, KozlovKV commented
Влей develop в свою ветку

2024-02-20 02:23 UTC, KozlovKV commented
> Если указывать относительный путь, как в примере выше, то могут возникнуть проблемы при исполнении кода. У меня не получалось нормально сынтерпретировать его в VS Code. Пришлось при АКТИВИРОВАННОЙ виртуальной среде исполнять в терминале: `(.venv) \ПОЛНЫЙ_ПУТЬ\> python visualizer.py`

Вообще, раньше у нас было также вроде как. И в целом можно пока что так и оставить, но, конечно, вариант несколько костыльный, так что вот пара решений, которые пришли мне в голову:
1. Добавить в корень sh/bat скрипт для запуска утилиты, тогда путь можно будет указывать из корня проекта, но надо будет следить сразу за двумя скриптами, а это не гуд
2. Записывать в конфиг отдельными параметрами абсолютный путь до корня проекта и относительный путь до файла с точками от корня. Задача потом будет сводиться к комбинированию этих путей. Такой вариант позволит запускать путь откуда удобно и в перспективе очень легко перенести передачу пути до файла в аргументы

2024-02-20 02:32 UTC, KozlovKV commented
Варианта выше не обязательно сейчас реализовывать)
Выглядит как неплохая таска (кусок таски) на следующую неделю

Ещё вот какие мысли возникли:
- Добавить возможность скейлинга по осям
- Описать, как добавлять точкам цвета (пока что мы из основной проги не узнаём цвета, но в будущем это станет акутально
- Описать в `README.md` управление

2024-02-20 02:39 UTC, AntonTsoy commented on .gitignore
> +data/
Может тогда лучше наоборот создать папку `dynamic`. Она будет лежать внутри `data`, в неё будем складывать все большие файлы и просто те, которыми не захотим делиться. Так у нас будет всего одна запись - `data/dynamic`  в `.gitignore`

2024-02-20 02:46 UTC, KozlovKV commented on .gitignore
> +data/
Не нравится мне всё же такая вложенность папки `data`... Предлагаю её строго определить под динамические данные, то есть просто её саму включить в игнор, а для того, что будет индексироваться, выделить папку... `resources` мне нравится больше, чем `static` пожалуй

2024-02-20 02:49 UTC, KozlovKV commented on .gitignore
> +data/
В таком случае у нас будет следующее разделение:
- `data` - плоды работы проги
- `resources` - индексируемые файлы, используемые для работы или тестирования

Сейчас понял, что кое-какой момент такое разделение не учитывает: при таком логическом разделении пихать в папку `data` большие файлы будет не очень гуд, поэтому... Либо мы снова обзаводимся вложенностью и добавляем в игнор `resources/private` (или другое название), либо просто оставляем на устроение каждого, какой путь до файлов указывать.

Я бы на самом деле предложил второй вариант, потому что ведь в перспективе и путь до файла у нас будет передаваться через командную строку

2024-02-20 03:14 UTC, AntonTsoy commented
Пример config.py на данный момент:
```python
PROJECT_PATH = "C:/SLAM-code/"
VIZ_FILE_PATH = "data/points.txt"
VIZ_PARSE_FORMAT = "xyz"
```

2024-02-20 05:01 UTC, KozlovKV approved these changes

2024-02-20 12:00 UTC, merged