Feature matching
FIT-2023-SLAM-indoor/slam-indoor-code pull request #36
Opened 2024-02-25 05:39 UTC by IgorShal

New defines for config:
```c++
//Use FT instead on FM
#define FT_ACTIVATE 
//Choose your matcher:
#define FM_SIFT_FLANN
//#define FM_SIFT_BF
//#define FM_ORB

//It's just fm's work visualization
#define SHOW_TRACKED_POINTS1

```

2024-02-25 15:21 UTC, KozlovKV requested changes

2024-02-25 15:21 UTC, KozlovKV commented on src/featureMatching.cpp
> +#endif
Можно использовать в комбинации с `#ifdef` также `#elifdef`, а в блоке `#else` кидать исключение, тогда и выглядеть будет чуть приятнее, и гарантировать сможем, что один из матчеров будет выбран

2024-02-25 15:21 UTC, KozlovKV commented on src/featureMatching.cpp
> +	extractor = cv::SIFT::create();
Добавишь дэфайны для параметров матчинга (тут и, возможно, в других местах)? Будем подбирать параметры для получения ещё более приятного результата

2024-02-25 15:21 UTC, KozlovKV commented on src/photosProcessingCycle.cpp
>              cvtColor(currentFrame, currentFrame, COLOR_BGR2GRAY);
Я проверил, вроде как конвертация в серый не сказывается негативно на матчинге, но в целом, наверное, можно обернуть эту конвертацию в `#ifdef FT_ACTIVATE`

2024-02-29 15:29 UTC, KozlovKV approved these changes

2024-02-29 15:29 UTC, KozlovKV commented on src/featureMatching.cpp
> +	matcher->radiusMatch(prevImgDesc, curImgDesc, matches, FM_SEARCH_RADIUS);
Напиши комментарием новые поля конфиг-файла

2024-02-29 15:52 UTC, IgorShal commented on src/featureMatching.cpp
> +	matcher->radiusMatch(prevImgDesc, curImgDesc, matches, FM_SEARCH_RADIUS);
Сверху

2024-02-29 16:04 UTC, merged