Formating of points coordinates
FIT-2023-SLAM-indoor/slam-indoor-code pull request #38
Opened 2024-02-25 13:35 UTC by AntonTsoy

2024-02-25 14:25 UTC, IgorShal commented
Можешь, пожалуйста, написать, что ты сделал либо здесь, либо в ноушене.

2024-02-25 15:32 UTC, KozlovKV requested changes
Открывать каждый раз файл, даже если открывать в режиме append всё же дорогая операция, поэтому предлагаю разделить функцию на 2: первая будет писать матрицу в переданный поток и в конце флашить его, а вторая будет производить открытие по имени. В циклах нужно будет использовать первую из этих функций, а вторая пусть будет на всякий случай

2024-02-25 15:32 UTC, KozlovKV commented on src/IOmisc.cpp
> +void rawOutput(const Mat &matrix, const String &path) {
А точно ли будет эта функция работать в режиме append?

2024-02-25 15:32 UTC, KozlovKV commented on src/photosProcessingCycle.cpp
>      std::ofstream poseStream;
На самом деле для потоков, куда будут писаться позиции камеры, тоже нужно сделать так, но... Напишу в комменте подробнее

2024-02-25 15:33 UTC, AntonTsoy commented on src/IOmisc.cpp
> +void rawOutput(const Mat &matrix, const String &path) {
она будет работать в режиме `write`. Все, что было в файле заменяется на новую запись. Мы по-моему с тобой обсуждали такой режим, но видимо я перепутал. Исправлю

2024-02-25 15:40 UTC, AntonTsoy commented
@IgorShal : По сути я перенёс пару функций из `cameraCalibration` в относительно новый файл `IOmisc`. Соответственно пришлось адаптировать includ-ы. Еще я написал функцию `rawInput` для записи координат точек в файл в нужном формате, но после замечаний Кирилла, написанных выше, она полетит в мусор...

2024-02-25 15:45 UTC, KozlovKV commented on src/IOmisc.cpp
> +void rawOutput(const Mat &matrix, const String &path) {
Хм... Вроде говорили, да, но речь шла про `append`, хотя не уверен. В этой функции исправлять не надо. Она пусть будет как раз такой для разовой записи (либо можно добавить третий аргумент для выбора режима), а в функции, принимающей поток, выбор режима ляжет на того, кто создавал поток

2024-02-25 15:46 UTC, KozlovKV commented
> @IgorShal : По сути я перенёс пару функций из `cameraCalibration` в относительно новый файл `IOmisc`. Соответственно пришлось адаптировать includ-ы. Еще я написал функцию `rawInput` для записи координат точек в файл в нужном формате, но после замечаний Кирилла, написанных выше, она полетит в мусор...

Неправда! Она видоизменится и размножится на 2, но большая часть когда останется такой же

2024-02-25 16:02 UTC, IgorShal commented
А можешь добавить инструменты для умножения точек на коэффиценты, как раньше было. Наверное, это надо в сам файл пайтона добавлять, чтобы можно было менять, не запуская заново весь алгоритм.

2024-02-27 02:19 UTC, AntonTsoy commented on src/photosProcessingCycle.cpp
>      std::ofstream poseStream;
так и не написал. Но я кажется уже понял

2024-02-28 02:25 UTC, AntonTsoy commented
Надо бы ещё потестировать работу с учетом правок

2024-02-28 12:04 UTC, KozlovKV approved these changes

2024-02-28 12:46 UTC, AntonTsoy commented
Протестировал, все хорошо работает

2024-02-28 12:46 UTC, merged