New structures FOR ALL
FIT-2023-SLAM-indoor/slam-indoor-code pull request #40
Opened 2024-02-28 12:06 UTC by KozlovKV

Учитывая, что изменения в любом случае коснутся всех нас, предлагаю действовать так:
- От этой ветки создаём ветки для внесения своих изменений в соответствии с новой структурой данных
- Вливаем изменения обратно в эту ветку
- Когда всё у всех будет готово, вливаем эту ветку в develop и радуемся жизни (I hope...)

2024-02-28 12:19 UTC, KozlovKV commented
Затронуты новой структурой будут многие файлы. Учитывая сжатые сроки, думаю, отдельные функции можно писать сразу на основании прежних и той статьи, потом всё должно будет плюс-минус нормально слиться.

Каждому создам отдельные таски

2024-02-28 12:27 UTC, AntonTsoy requested changes

2024-02-28 12:27 UTC, AntonTsoy commented on src/mainCycle.h
> +    int size; /// количество кадров, инфа о которых есть сейчас
А, Кирилл, я забыл сказать один важный факт из лекции по QA от Мокина. Он сказал, что хорошие, понятные имена переменных дают много бонусов: 1) защиту от глупых ошибок; 2) возможность не писать комментарии и документацию к коду; 3) легкость чтения и восприятия кода (хотя... это вытекает из 1 и 2 пункта, или наоборот)

2024-02-28 12:27 UTC, AntonTsoy commented on src/mainCycle.h
> +    std::vector<std::vector<KeyPoint>> allFeatures; // Все заэкстратенные фичи i-го кадра
allExtractedFeatures

2024-02-28 12:27 UTC, AntonTsoy commented on src/mainCycle.h
> +    std::vector<Vec3b> colors; // Цвета трёхмерных точек
colors3dPoints

2024-02-28 13:15 UTC, KozlovKV commented on src/mainCycle.h
> +    int size; /// количество кадров, инфа о которых есть сейчас
Ну комменты итак временные

2024-02-28 13:16 UTC, KozlovKV commented on src/mainCycle.h
> +    int size; /// количество кадров, инфа о которых есть сейчас
А насчёт имён полностью согласен. Сейчас поменяю

2024-02-28 13:26 UTC, KozlovKV commented
Пока переименовывал переменные, пришёл к очевидному выводу, что мега-структура - это не гуд, особенно когда мы хотим одну её часть чистить, а другую - нет. Поэтому предлагаю сделать 2 структуры. Теперь в первой уже не вектора векторов, так как сами объекты структуры будут храниться в векотре

2024-02-28 13:35 UTC, AntonTsoy commented on src/mainCycle.h
> +    int size; /// количество кадров, инфа о которых есть сейчас
я не против комментов, я за хорошие имена. Про комменты просто как фан факт написал

2024-02-29 16:12 UTC, KozlovKV commented
@AntonTsoy , @IgorShal , подлил сюда актуальную версию develop. Можно приступать к таскам по переработке

2024-03-02 05:00 UTC, KozlovKV commented
> Нам вектор матчей нахрен не нужен, не вижу смысла его хранить в темп дате

Нужен будет для этой функции - `get_objpoints_and_imgpoints()` (https://programmerall.com/article/3640516928/)

2024-03-14 03:13 UTC, KozlovKV commented
@KozlovKV , @AntonTsoy , @IgorShal 

Основной цикл рефакторинга завершён. Впереди ещё много работы, но и эта была не малой. С верой в светлое будущее, вливаем в `develop`!

2024-03-16 13:09 UTC, merged