FM refactor
FIT-2023-SLAM-indoor/slam-indoor-code pull request #42
Opened 2024-03-01 12:13 UTC by IgorShal

2024-03-01 12:20 UTC, IgorShal commented
К сожалению, я не могу из воздуха матчить фичи только по их координатам, в функцию матчинга, как минимум, нужно подавать ещё и кадры, из которых взяты фичи, + нужно как-то выбрать тип матчера, ну, можно это в конфиге настраивать.

2024-03-01 15:33 UTC, KozlovKV requested changes
Сорри за кривой инглиш 😅
Исправил формулировку в таске

2024-03-02 07:08 UTC, KozlovKV requested changes
Вообще, сначала думал, что общая обёртка нам не подойдёт вовсе, но сейчас мне кажется, что если наружу из неё также возвращать матчи, то будет даже и норм.

Ещё несколько общих моментов:
- Добавь к типам аргументов `const`, где это нужно. Так мы сразу сможем заметить, если где-то будет изменяться то, что изменяться не должно (в частности, нельзя менять вектора `KeyPoint`ов - вроде этого нигде и не происходит, но всё же)
- Добавить докстринги. Даже не обязательно их подробно расписывать, но укажи, какие параметры `[in]`, а какие `[out]`

2024-03-02 07:08 UTC, KozlovKV commented on src/featureMatching.cpp
> +		prevDesc, curDesc, matcherType, matches, radius);
`prevDesc` и `curDesc` используются и даже считаются внутри `extractDescriptorsAndMatch`, поэтому передавать их аргументами не вижу смысла

2024-03-02 07:08 UTC, KozlovKV commented on src/featureMatching.cpp
> +	std::vector<Point2f>& matchedFeatures, std::vector<Point2f>& newPreviousFeatures, int matcherType, int radius, bool showMatchedPoints) {
`radius` в матчере используется типа `float`. Хотя мы и пишем туда сейчас в основном интовые значения. Для большей свободы в задании параметров, думаю, лучше его и передавать флотовым

2024-03-02 07:08 UTC, KozlovKV commented on src/featureMatching.cpp
> +			throw std::exception("No such type");
CLion подсвечивает эту штуку красным, говоря, что не хочет принимать `char[]`. Если оставить скобки пустыми, всё становится нормально. Пока что предлагаю так и сделать, а подробнее с исключениями разобраться потом

2024-03-02 07:08 UTC, KozlovKV commented on src/featureMatching.cpp
Чисто стилевой момент, который относится ко всем функциям: не очень хорошо, когда у аргументов в скобках такой же отступ как и тела функции. CLang-tidy обычно предлагает просто делать его больше, но Вова и на такой вариант агрился, так что предлагаю оформлять так:
- На одной строке имя функции и открывающая скобка
- На следующих строках аргументы с отступом в один таб
- На новой строке строке закрываем скобку и открываем тело цикла (`) {`)

2024-03-02 07:08 UTC, KozlovKV commented on src/featureMatching.cpp
> +void getMatchedPoints(Mat& previousFrame, Mat& currentFrame, std::vector<KeyPoint>& previousFeatures, std::vector<KeyPoint>& currentFeatures,
Предлагаю назвать `matchPoints` либо `processFeatureMatching`

2024-03-02 07:08 UTC, KozlovKV commented on src/featureMatching.cpp
> +void getGoodMatches(std::vector<KeyPoint>& previousFeatures, std::vector<KeyPoint>& currentFeatures,
А эту назвать как раз `getMatchedPoints` либо как-то ещё, чтобы было понятно, что она именно заполняет новые вектора точек

2024-03-05 07:56 UTC, AntonTsoy commented
Лайк за рефакторинг!

2024-03-05 16:02 UTC, KozlovKV requested changes
Получается, что для получения матчей нам нужно дважды вызывать `extractDescriptor()`, а потом `matchFeatures()`? Если так, то будто бы это в главном цикле делать не особо приятно. Может внутри `matchFeatures()` в начале вызывать `extractDescriptor()`ы. Ну и соответствующим образом входные аргументы поменять.

Как только это сделаешь, можно будет вливать ветку

2024-03-05 16:23 UTC, AntonTsoy commented
Хах, я на своей ветке уже написал отдельную функцию в `featureMatching.cpp`
```cpp
void matchFramesPairFeatures(
	Mat& firstFrame,
	Mat& secondFrame,
	std::vector<KeyPoint>& firstFeatures,
	std::vector<KeyPoint>& secondFeatures,
	int matcherType,
	float radius,
	std::vector<DMatch>& matches
) {
	Mat firstDescriptor;
	extractDescriptor(firstFrame, firstFeatures, matcherType, firstDescriptor);
	Mat secondDescriptor;
	extractDescriptor(secondFrame,secondFeatures, matcherType, secondDescriptor);
	matchFeatures(firstDescriptor, secondDescriptor, matches, matcherType, radius);
}
```

2024-03-07 15:14 UTC, AntonTsoy commented
Отмена, я перенес эту функцию в `mainCycle`, у нее поменялась сигнатура

2024-03-07 17:20 UTC, KozlovKV commented
> Отмена, я перенес эту функцию в `mainCycle`, у нее поменялась сигнатура

Ладно. Предлагаю в файл матчера перенести её после окончания всего рефакторинга

2024-03-07 17:20 UTC, KozlovKV approved these changes

2024-03-07 17:20 UTC, merged