Redesign cycle
FIT-2023-SLAM-indoor/slam-indoor-code pull request #45
Opened 2024-03-05 15:38 UTC by AntonTsoy

2024-03-08 16:09 UTC, IgorShal commented
Тестил? Работает?

2024-03-08 16:59 UTC, AntonTsoy commented
нет

2024-03-09 06:04 UTC, IgorShal requested changes

2024-03-09 06:04 UTC, IgorShal commented on src/mainCycle.cpp
> +void getMatchedPoints(
Эта функция уже есть в featureMatching.cpp

2024-03-09 06:04 UTC, IgorShal commented on src/mainCycle.cpp
> +    Mat secondFrame;
Mat secondFrame принимает  функция  processingFirstPairFrames

2024-03-09 06:04 UTC, IgorShal commented on src/mainCycle.cpp
> +void videoCycle(
Этой функции нет в хедере.

2024-03-09 06:24 UTC, AntonTsoy commented
Мне надо было вас предупредить, что я сел допиливать код...
Часть код ревью уже не актуальна. Сделайте git pull

2024-03-10 06:29 UTC, IgorShal commented
Приблизительный мейн для теста:

```c
#include "cameraCalibration.h"
#include "IOmisc.h"
#include "mainCycle.h"
#include <cstdio>
#include <fstream>
#include <iostream>
#include "nlohmann/json.hpp"
#include "config/config.h"

#include "main_config.h"

using namespace cv;
using json = nlohmann::json;

ConfigService configService;

int main(int argc, char** argv)
{

	configService.setConfigFile("../config.json");

	std::cout << configService.getValue<std::string>(ConfigFieldEnum::CALIBRATION_PATH_);

    VideoCapture cap(VIDEO_SOURCE_PATH);
	if (!cap.isOpened()) {
		std::cerr << "Camera wasn't opened" << std::endl;
		return -1;
	}
	char path[] = OUTPUT_DATA_DIR;
	/*videoProcessingCycle(cap,
                         FT_BARRIER,
                         FT_MAX_ACCEPTABLE_DIFFERENCE,
                         FRAMES_BATCH_SIZE,
                         REQUIRED_EXTRACTED_POINTS_COUNT,
                         FEATURE_EXTRACTING_THRESHOLD,
                         path);
    */
    videoCycle(cap, FRAMES_BATCH_SIZE,  FEATURE_EXTRACTING_THRESHOLD,  REQUIRED_EXTRACTED_POINTS_COUNT,
    REQUIRED_EXTRACTED_POINTS_COUNT ,1, FM_SEARCH_RADIUS_);
    return 0;
}
```

2024-03-10 07:03 UTC, KozlovKV requested changes
Получается, в процессе написания цикла, ты его не тестировал, если нет какого-то кода для запуска в мэйне? Так можно делать, когда пишешь какой-то небольшой кусок кода, но когда такой значительный, это очень опасно. Когда будешь дописывать, обязательно запускай цикл - это поможет очень многие моменты быстро отловить

2024-03-10 07:03 UTC, KozlovKV commented on src/mainCycle.cpp
> +    int frameBatchSize,
Как мне кажется (можете со мной и не согласиться), с новым вариантом конфига не нужно передавать все параметры как аргументы (а то если что-то захотим добавить, нужно будет менять декларацию функции в хэрэре и т.д.), то есть можно оставить в качестве аргумента только `VideoCapture`, а остальное получать через `configService` (см. следующий коммент)

2024-03-10 07:03 UTC, KozlovKV commented on src/mainCycle.cpp
> +void defineProcessingConditions(
Соответственно, эта функция также может не принимать аргументов кроме структуры. То есть внутри этой функции будут делаться запросы к `configService`, через которые мы и заполним структуру

Ещё вариант - вообще не использовать структуру, а просто везде обращаться к `configService` (это не чтение из файла, так что операция недорогая), но строки с таким запросом будут длинные и немного громоздкие, так что структура сама по себе мне кажется хорошей идеей

2024-03-10 07:03 UTC, KozlovKV commented on src/mainCycle.cpp
> +    std::vector<KeyPoint> &previousFeatures,
Не только применительно к этому полю, а вообще ко многим:
1. Безопаснее маркировать входные данные как `const`, чтобы точно не допустить их изменений
2. Лучше не перемешивать входные и выходные данные, а сначала передавать в функцию одни, потом другие (но есть много случаев, где ради логики можно отойти от этого условия)

2024-03-10 07:03 UTC, KozlovKV commented on src/mainCycle.cpp
> +void matchFramesPairFeatures(
Думаю, эту функцию имеет смысл перенести в `featureMatching.cpp`/`.h`

2024-03-10 07:03 UTC, KozlovKV commented on src/mainCycle.cpp
> +void maskoutPoints(const Mat &chiralityMask, std::vector<Point2f> &extractedPoints) {
Вроде в `cameraTransition.cpp` уже есть неплохая версия этой функции - `filterVectorByMask()`. Отличия у них минимальные (только та, в случае чего, может транспонировать матрицу) + сейчас добавил также проверку корректности. Если решишь, что твоя лучше, то в любом случае перенеси её в `cameraTransition.cpp`

2024-03-10 07:03 UTC, KozlovKV commented on src/mainCycle.cpp
> +    computeTransformationAndMaskPoints(dataProcessingConditions, chiralityMask,
А вот тут серьёзная ошибка. Для расчёта матрицы вращения и сдвига нам нужны только заматченные точки, то есть надо вызывать сначала `getMatchedPoints()` из `featureMatching.cpp`, который и заполнит вектора, а потом уже `computeTransformationAndMaskPoints`, который сразу будет принимать `vector<Point2f>`

2024-03-10 07:03 UTC, KozlovKV commented on src/mainCycle.cpp
> +    KeyPoint::convert(prevFrameData.allExtractedFeatures, extractedPointCoords1);
Следуя прошлом комменту, эти 2 строчки не нужны, а также изменится сигнатура функции

2024-03-10 07:03 UTC, KozlovKV commented on src/mainCycle.cpp
> +void getMatchedPointCoords(
Также перенеси в `featureMatching.cpp` либо используй версию, которая там уже есть (та самая `getMatchedPoints()`)

2024-03-10 07:03 UTC, KozlovKV commented on src/mainCycle.cpp
> +        getMatchedPointCoords(temporalImageDataDeque.at(lastGoodFrameIdx).allExtractedFeatures,
См. коммент над этим

2024-03-10 07:03 UTC, KozlovKV commented on src/mainCycle.cpp
> +            temporalImageDataDeque.pop_front();
Если я верно понял, в какой-то момент дэка у нас просто опустее, и при любых обращениях мы будет ловить RuntimeException.

Думаю, с дэкой нужно провести ряд изменений:
1. Задавать ей изначально размер 2 и заполнять для двух первых кадров
2. В основном цикле, когда нашли новый хороший кадр, добавляем новый элемент в хвост дэки (проводя его очистку и всё, что нужно для инициализации элемента)
3. Если в конце цикла обнаружили, что размер дэки достиг потолка, вынимаем из неё элемент

Индексацию в цикле в таком случае можно организовать так:
1. Добавили структуру нового кадра в дэку
2. Получили размер дэки (скажем, `currIndex`)
3. Обращаемся теперь к структуре прошлого хорошего кадра как `currIndex-1`, а к текущей просто по `currIndex`

2024-03-10 07:03 UTC, KozlovKV commented on src/mainCycle.h
>  using namespace cv;
Здесь общий момент по организации модуля:
1. Не вижу большого смысла добавлять в хэдэр все функции, так как бОльшая их часть используется только внутри самого модуля
2. В самом `.cpp` файле, как мне кажется, имеет смысл расположить сначала основную функцию цикла, а ниже, в порядке их появления, располагать остальные функции (если мы их уберём из хэрэра и сделаем `static`, то можно сначала в `.cpp` расположить декларации, потом главную функцию, а потом реализации)

2024-03-10 07:09 UTC, AntonTsoy commented on src/mainCycle.cpp
> +void defineProcessingConditions(
Ну вот, да, с последним согласен. Строка запроса к `configService` мне не нравится, поэтому структуру я бы предпочел оставить

2024-03-10 07:12 UTC, AntonTsoy commented on src/mainCycle.cpp
> +void matchFramesPairFeatures(
Тогда ей надо переписать сигнатуру (т.е. поменять параметры), либо структуру `dataProcessingConditions` тоже куда-то в другое место перенести

2024-03-10 07:13 UTC, AntonTsoy commented on src/mainCycle.cpp
> +    std::vector<KeyPoint> &previousFeatures,
Как я понимаю это не тот случай, когда по пункту 2 можно сделать исключение?

2024-03-10 07:14 UTC, AntonTsoy commented on src/mainCycle.cpp
> +void maskoutPoints(const Mat &chiralityMask, std::vector<Point2f> &extractedPoints) {
Я просто не знал, что у нас есть подобная функция

2024-03-10 07:16 UTC, AntonTsoy commented on src/mainCycle.cpp
> +    computeTransformationAndMaskPoints(dataProcessingConditions, chiralityMask,
Хорошо, что ты заметил. Я обязательно исправлю, но наверное не сегодня

2024-03-10 07:19 UTC, AntonTsoy commented on src/mainCycle.cpp
> +    int frameBatchSize,
Я только "за", чтобы у функций было меньше параметров

2024-03-10 07:22 UTC, AntonTsoy commented on src/mainCycle.h
>  using namespace cv;
хорошо, как раз, когда писал все это в хэдеэр, задумался на эту тему...

2024-03-10 07:25 UTC, KozlovKV commented on src/mainCycle.cpp
> +        undistort(candidateFrame, goodFrame,
Предлагаю пока его не использовать. До этого практика показала, что результат становится хуже

2024-03-10 07:27 UTC, KozlovKV commented on src/mainCycle.cpp
> +    std::vector<KeyPoint> &previousFeatures,
Да почему же. Добавь `const` - и уже будет при беглом взгляде в разы понятнее

2024-03-10 07:29 UTC, KozlovKV commented
@AntonTsoy , @IgorShal , запушил прямо сюда вызов мэйна с взятием прямо из конфигов данных + кое-какие правки внёс в другие файлы. Теперь... Теперь он падает по каким-то ассёртам, но с этим уже можно работать

В общем, сделайте `git pull`

2024-03-10 07:42 UTC, AntonTsoy commented on src/mainCycle.cpp
> +            temporalImageDataDeque.pop_front();
Дэк не должен опустеть. Хотя я так хреново делаю эту таску, что может и в каком-то случае и опустеет.
Ладно, постараюсь объяснить почему дэк не должен опустеть:
Изначально размер дека задаётся равным `OPTIMAL_DEQUE_SIZE` (пока что это 8). Мы вызываем функцию обработки первых двух хороших кадров, если такие кадры не были найдены прога завершиться с кодом (-1) - дэк не опустел. Случай, когда нашли два хороших кадра: мы заполнили первые два элемента дэка из восьми данными, запускаем цикл по добавлению следующих хороших кадров (тут `lastGoodFrameIdx` равен 1).
Если нам в батче не удалось найти хороший кадр, цикл просто завершается - дэк не пустой. Допустим мы нашли в нескольких батчах подряд по хорошему кадру (просто инкрементируем `lastGoodFrameIdx`). Теперь пускай у нас `lastGoodFrameIdx` равен 6 (есть данные о 7 хороших кадрах). Если мы нашли 8-ой хороший кадр, то удаляется самый первый элемент, все кадры сдвигаются на одну позицию в сторону начала (в дэке 7 кадров).
Дальше мы действуем аналогично: 1) как только в батче не нашли хороший кадр - завершаем цикл (дэк не пуст); 2) нашли новый хороший кадр - удаляем самый старый кадр, происходит сдвиг остальных. У нас в видео с большим количеством хороших кадров, почти все время (кроме самого начала) будет лежать в конце каждой итерации 7 кадров (в начале следующей будет добавляться восьмой)

2024-03-10 07:45 UTC, AntonTsoy commented
Эм, ну, тут в чем проблема: всё, что делает функция `videoCycle` (на данный момент) - это создает на куче объекты структур для хранения мета информации о видеокадрах, а потом, после окончания работы, эти объекты просто уничтожаются (хотя, если StackOverflow врёт, то получается объекты из OpenCV не уничтожаться, будут занимать память, а мы просто потеряем ссылку на них, что ещё хуже; так что надеюсь StackOverflow говорит правду). Так вот то есть эта функция просто запуститься, что-то там поделает и завершиться, никакой обратной связи она не вернёт, ничего не выведет на экран и ничего не запишет в какой-нибудь аргумент, который мы ей передали. Поэтому её сейчас невозможно протестировать.
Надо что-то в ней переписать, но не знаю что лучше сделать:
1) Можно, чтобы структуры `GlobalData` и `TemporalImageData` создавались, где-то снаружи и в качестве [out] аргументов передавались `videoCycle`
2) а другого ничего я и не придумал...

2024-03-10 07:51 UTC, AntonTsoy commented on src/featureMatching.cpp
> +	if (configService.getValue<bool>(ConfigFieldEnum::FM_SIFT_FLANN_))
Как я понял, Игорь SIFT_FLANN приоритетнее ставил. И по документу сравнения матчеров - у него точность выше остальных

2024-03-10 07:58 UTC, KozlovKV commented on src/featureMatching.cpp
> +	if (configService.getValue<bool>(ConfigFieldEnum::FM_SIFT_FLANN_))
Я расположил их в порядке нумерации, который был. Не предполагается, что у нас будет стоять `true` у нескольких видов матчеров сразу, но сейчас такое действительно возможно. Учитывая, что выбор матчера - временная фишка (скорее всего), думаю, пока что можно просто держать это в голове и не ломать конфиг таким образом

2024-03-10 08:00 UTC, KozlovKV commented
> Эм, ну, тут в чем проблема: всё, что делает функция `videoCycle` (на данный момент) - это создает на куче объекты структур для хранения мета информации о видеокадрах, а потом, после окончания работы, эти объекты просто уничтожаются (хотя, если StackOverflow врёт, то получается объекты из OpenCV не уничтожаться, будут занимать память, а мы просто потеряем ссылку на них, что ещё хуже; так что надеюсь StackOverflow говорит правду). Так вот то есть эта функция просто запуститься, что-то там поделает и завершиться, никакой обратной связи она не вернёт, ничего не выведет на экран и ничего не запишет в какой-нибудь аргумент, который мы ей передали. Поэтому её сейчас невозможно протестировать. Надо что-то в ней переписать, но не знаю что лучше сделать:
> 
> 1. Можно, чтобы структуры `GlobalData` и `TemporalImageData` создавались, где-то снаружи и в качестве [out] аргументов передавались `videoCycle`
> 2. а другого ничего я и не придумал...

В любом случае она должна будет исполниться до конца без непредусмотренных падений. А насчёт обратной связи: почему бы не выводить в файлы также инфу, как это было прежде? С тем лишь учётом, что местами у нас теперь вектора, а значит просто передать их в поток через `<<` не выйдет - нужна доп. функция в `IOmisc`

2024-03-10 08:01 UTC, AntonTsoy commented on src/featureMatching.cpp
> +	if (configService.getValue<bool>(ConfigFieldEnum::FM_SIFT_FLANN_))
ок

2024-03-10 08:02 UTC, KozlovKV requested changes

2024-03-10 08:02 UTC, KozlovKV commented on src/mainCycle.cpp
> +            matchedPointCoords1, matchedPointCoords2, newSpatialPoints);
Далее надо будет сделать умную функцию для вливания `newSpatialPoints` к остальным трёхмерным точкам из `globalData`, а пока что предлагаю просто добавить слияние этих векторов

2024-03-10 08:05 UTC, AntonTsoy commented
> > Эм, ну, тут в чем проблема: всё, что делает функция `videoCycle` (на данный момент) - это создает на куче объекты структур для хранения мета информации о видеокадрах, а потом, после окончания работы, эти объекты просто уничтожаются (хотя, если StackOverflow врёт, то получается объекты из OpenCV не уничтожаться, будут занимать память, а мы просто потеряем ссылку на них, что ещё хуже; так что надеюсь StackOverflow говорит правду). Так вот то есть эта функция просто запуститься, что-то там поделает и завершиться, никакой обратной связи она не вернёт, ничего не выведет на экран и ничего не запишет в какой-нибудь аргумент, который мы ей передали. Поэтому её сейчас невозможно протестировать. Надо что-то в ней переписать, но не знаю что лучше сделать:
> > 
> > 1. Можно, чтобы структуры `GlobalData` и `TemporalImageData` создавались, где-то снаружи и в качестве [out] аргументов передавались `videoCycle`
> > 2. а другого ничего я и не придумал...
> 
> В любом случае она должна будет исполниться до конца без непредусмотренных падений. А насчёт обратной связи: почему бы не выводить в файлы также инфу, как это было прежде? С тем лишь учётом, что местами у нас теперь вектора, а значит просто передать их в поток через `<<` не выйдет - нужна доп. функция в `IOmisc`

можно и так, как раз хотел спросить, как юзать структуру `LogFiles`. Мне получается писать в потоки так, же как это делалось раньше?

2024-03-10 08:12 UTC, KozlovKV commented on src/mainCycle.cpp
> +            temporalImageDataDeque.pop_front();
Может быть я в упор не замечаю, где ты добавляешь в хвост дэки новый элемент, но если этого нет, то мы через 8 итераций вынем из дэки все элементы, то есть она будет пустой. Вот такой код выдаст ошибку:
```c++
        std::deque<int> deque(5);
	deque.at(4) = 5;
	while (!deque.empty()) {
		std::cout << "Deque sz: " << deque.size() << "; 1st elem: " << deque.front() << std::endl;
		deque.pop_front();
	}
	std::cout << deque.at(4) + 1;
	return 0;
```
Вывод:
```bash
Deque sz: 5; 1st elem: 0
Deque sz: 4; 1st elem: 0
Deque sz: 3; 1st elem: 0
Deque sz: 2; 1st elem: 0
Deque sz: 1; 1st elem: 5
terminate called after throwing an instance of 'std::out_of_range'
  what():  deque::_M_range_check: __n (which is 4)>= this->size() (which is 0)
```

2024-03-10 08:13 UTC, KozlovKV commented
> > > Эм, ну, тут в чем проблема: всё, что делает функция `videoCycle` (на данный момент) - это создает на куче объекты структур для хранения мета информации о видеокадрах, а потом, после окончания работы, эти объекты просто уничтожаются (хотя, если StackOverflow врёт, то получается объекты из OpenCV не уничтожаться, будут занимать память, а мы просто потеряем ссылку на них, что ещё хуже; так что надеюсь StackOverflow говорит правду). Так вот то есть эта функция просто запуститься, что-то там поделает и завершиться, никакой обратной связи она не вернёт, ничего не выведет на экран и ничего не запишет в какой-нибудь аргумент, который мы ей передали. Поэтому её сейчас невозможно протестировать. Надо что-то в ней переписать, но не знаю что лучше сделать:
> > > 
> > > 1. Можно, чтобы структуры `GlobalData` и `TemporalImageData` создавались, где-то снаружи и в качестве [out] аргументов передавались `videoCycle`
> > > 2. а другого ничего я и не придумал...
> > 
> > 
> > В любом случае она должна будет исполниться до конца без непредусмотренных падений. А насчёт обратной связи: почему бы не выводить в файлы также инфу, как это было прежде? С тем лишь учётом, что местами у нас теперь вектора, а значит просто передать их в поток через `<<` не выйдет - нужна доп. функция в `IOmisc`
> 
> можно и так, как раз хотел спросить, как юзать структуру `LogFiles`. Мне получается писать в потоки так, же как это делалось раньше?

Да

2024-03-10 08:26 UTC, AntonTsoy commented on src/mainCycle.cpp
> +            temporalImageDataDeque.pop_front();
Ладно, я лох. Я действительно нигде не делал .push_back(). Вангую, сейчас мой код упадет уже после первого удаления. Сразу .pop_front, надо делать .push_back() нового объекта `TemporalImageData`

2024-03-10 10:16 UTC, IgorShal requested changes

2024-03-10 10:16 UTC, IgorShal commented on src/mainCycle.cpp
> +void getMatchedPointCoords(
эта функция буквально уже есть в fm.cpp, полная её копия, ладно, могу убрать её оттуда

2024-03-10 10:16 UTC, IgorShal commented on src/mainCycle.cpp
> +    estimateTransformation(
Тут надо подавать уже заматченные фичи, то есть предварительно вызвать getMatchedPoints, тогда конверты вообще не нужны. Проблема в том, что eT получает два равных по размеру вектора фич (потому что они соответствуют матчам) и по ним уже  оценивает трасформацию, а когда мы просто подаём два вектора экстрактнутых, мы идём *****, потому что их разное количество.

2024-03-10 10:16 UTC, IgorShal commented on src/mainCycle.cpp
> +void defineInitialCameraPosition(TemporalImageData initialFrame) {
Вроде здесь нужен & ,тогда данные корректно записываются.

2024-03-10 10:16 UTC, IgorShal commented on src/mainCycle.cpp
> +void getMatchedPointCoords(
Они абсолютно ничем не отличаются

2024-03-10 18:37 UTC, KozlovKV commented
Избавился от кое-каких ошибок, не дающих возможности запустить цикл:
1. Добавил амперсанд к аргументу `defineInitialCameraPosition()`
2. Добавил вливание новых трёхмерных точек к глобальным (дэ-факто хотел сделать не его, а в первую очередь заполнение поля `correspondSpatialPointIdx` у новых метаданных, потому что до этого там вылетал `SEGFAULT`)
3. Добавил строчку для того, чтобы дэка не опустошалась (вроде как всё нормально работает даже если в качестве структуры передать пустые фигурные скобки)
4. Пофиксил место с переводом векторов из `KeyPoint` в `Point2f`

2024-03-10 18:43 UTC, KozlovKV requested changes
Пока что кустарно пытаюсь выводить какие-то значения. Получаются они... Непонятными. С одной стороны, можно было бы напугаться числам порядка 10^-32, но возможно они просто все очень мелкие, а визуально будут отображаться нормально. Чтобы сказать наверняка, хотелось бы получать полный вывод по раздельным файликам

2024-03-10 18:43 UTC, KozlovKV commented on src/mainCycle.cpp
> +            break;
Насчёт этого момента ещё хотел сказать. Вообще, падать - не самая плохая идея, но возможно имеет смысл рассмотреть какое-то альтернативное поведение с повторным подбором двух начальных кадров

2024-03-11 01:17 UTC, AntonTsoy commented on src/mainCycle.cpp
> +void getMatchedPointCoords(
не надо

2024-03-11 01:32 UTC, AntonTsoy commented on src/mainCycle.cpp
> +void defineInitialCameraPosition(TemporalImageData initialFrame) {
Такая же херня с `initTemporalImageDataDeque`

2024-03-11 01:33 UTC, AntonTsoy commented on src/mainCycle.cpp
> +            break;
ок

2024-03-11 13:11 UTC, KozlovKV requested changes

2024-03-11 13:11 UTC, KozlovKV commented on src/mainCycle.cpp
> +    while (frameSequence.read(candidateFrame)) {
Вот какое у меня предложение насчёт быстрого сведения этого цикла к универсальному (и для фото, и для видео): во всех местах, где сейчас вызывается `frameSequence.read()` вместо этого вызывать функцию `getNextFrame()`, которая:
- Будет проверять через `configService`, какая сейчас версия цикла
- Если выбран фото-цикл, то будет брать следующий при помощи вектора строк с именами фоток
- Если видео-цикл (флаг фото-цикла = `false`), то будет брать следующий кадр из `frameSequence`
- При успешном взятии кадр будет записываться по переданной в эту функцию ссылке, а возвращать она будет `true`. В ином случае - `false`

В плане передачи аргументов мне пришёл в голову такой способ: создать структуру вроде `VideoSources`, в которой будут поля для `VideoCapture`, вектора `vector<string>` и индекса для его обхода (либо вместо двух последних можно использовать итератор, но если с этой штукой не знаком, то сейчас и заморачиваться не надо). Эту структуру будем передавать в те функции, куда сейчас передаётся `frameSequence`. Соответственно, сигнатура у новой функции будет такой: `bool getNextFrame(VideoSources& sources, Mat& nextFrame)`

2024-03-13 16:26 UTC, KozlovKV approved these changes

2024-03-13 16:30 UTC, KozlovKV commented
@AntonTsoy , @IgorShal 

На этом предлагаю закрыть PR, чтобы наконец работать, отпочковываясь от `develop`, а не от этой ветки. Тут ещё остались необходимые доработки, причём важные, так что дальше нк незакрытые замечания отсюда всё ещё имеет смысл опираться

Актуальные конфиги:

`config.json`:
```json
{
  "calibrate": false,
  "visualCalibration": true,
  "calibrationPath": "./config/samsung-hp.xml",

  "usePhotosCycle": true,
  "photosPathPattern": "/mnt/c/Users/bakug/YandexDisk/NSU/private/2-1/PAK/static/photos/samsung-table-s/*.JPG",
  // "videoSourcePath" has an effect when "usePhotosCycle" is false
  "videoSourcePath": "/mnt/c/Users/bakug/YandexDisk/NSU/private/2-1/PAK/static/samsung-hall.mp4",
  
  "outputDataDir": "./data/video_report/video_test",
  
  "useUndistortion": false,

  "requiredExtractedPointsCount": 50,
  "featureExtractingThreshold": 20,

  "framesBatchSize": 1,

  "useFeatureTracker": false,
  // This block has an effect when "useFeatureTracker" is true
  "useOwnFeatureTracker": true,
  "FTThreadsCount": 3,
  "useSADOwnFT": true,
  "useSSDOwnFT": false,
  "FTBarrier": 20,
  "FTMaxAcceptableDifference": 2000,
  
  // This block has an effect when "useFeatureTracker" is false
  "useFM-SIFT-FLANN": true,
  "useFM-SIFT-BF": false,
  "useFM-ORB": false,
  "featureMatchingRadius": 150.0,
  "showTrackedPoints": true,

  "RPUseRANSAC": true,
  "RPRANSACProb": 0.999,
  "RPRANSACThreshold": 5.0,
  "RPRequiredGoodPointsPercent": 0.5,
  "RPDistanceThreshold": 100.0
}
```

`config.py`:
```python
PROJECT_PATH = "/home/kirill/slam-indoor-code/"
VIZ_FILE_PATH = "data/points.txt"
VIZ_PARSE_FORMAT = "xyz"

SCALE = 1
```

2024-03-13 16:53 UTC, IgorShal approved these changes

2024-03-14 01:33 UTC, merged