SFM and VIZ test
FIT-2023-SLAM-indoor/slam-indoor-code pull request #49
Opened 2024-03-17 06:03 UTC by IgorShal

2024-03-17 06:30 UTC, IgorShal commented
Инструкция по установке из READ_ME
# slam-indoor-code
Repository with source code of SLAM indoor project

## Requirements
- OpenCV 4.8.0 
- CMake 3.26.2 ([release](https://github.com/Kitware/CMake/releases/tag/v3.27.6))


## Environment configuration
### OpenCV with libs installation
Короче, много всего попробовал точную последовательность не помню, напишу примерно
Использовал две статьи:
1. Для установки VIZ https://habr.com/ru/companies/intel/articles/217021/
просят libvtk5-dev но щас только libvtk7-dev
```sh
sudo apt-get install libvtk7-dev
```
2. Теперь ко второй статье https://bksp.space/blog/en/2020-03-01-compiling-opencv-with-structure-from-motion-module-python-bindings.html
```sh
sudo apt install build-essential
sudo apt install cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
#тут некоторые библиотеки могли не установится но пофиг
sudo apt install libeigen3-dev libgflags-dev libgoogle-glog-dev libatlas-base-dev libsuitesparse-
#тут вроде всё должно сработать
#теперь я не знаю, можно ли установить всё поверх нашего установщика, поэтому сделаем новый билд
mkdir opencv_build
cd opencv_build
#дальше просят установить керас, снизу есть гайд, как это сделать, но вот тут возможно лучше воспользовать гайдом из статьи, потому что сфм какого-то фига не видит керас поэтому пришлось вручную писать дефан что керас есть
git clone https://github.com/opencv/opencv.git
git clone https://github.com/opencv/opencv_contrib.git
#тут в статье предлагают менять названия реконстрактов в сфм потому что там 4 одинаковых но я ничего не менял
cd opencv
mkdir build
cd build
cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D OPENCV_EXTRA_MODULES_PATH=~/opencv_build/opencv_contrib/modules -D BUILD_SHARED_LIBS=ON -D BUILD_opencv_sfm=ON -D OPENCV_ENABLE_NONFREE=ON -D BUILD_SHARED_LIBS=ON  -D BUILD_TESTS=ON -D OPENCV_GENERATE_PKGCONFIG=ON -D BUILD_EXAMPLES=ON -D WITH_QT=ON -D WITH_GTK=ON -D WITH_OPENGL=ON -D WITH_FFMPEG=ON -D WITH_TBB=ON -D WITH_V4L=ON -D WITH_VTK=ON ..
#Объединение флагов первых двух статей и нашей инструкции к установки opencv 
make -j8
sudo make install
```



### Ceres installation
```sh
sudo apt-get install libeigen3-dev libgflags-dev libgoogle-glog-dev

wget http://ceres-solver.org/ceres-solver-2.2.0.tar.gz
tar zxf ceres-solver-2.2.0.tar.gz
mkdir ceres-bin
cd ceres-bin
cmake ../ceres-solver-2.2.0

make -j3
make test
sudo make install
```
Run for testing installation 
```sh
./bin/simple_bundle_adjuster ../ceres-solver-2.2.0/data/problem-16-22106-pre.txt
```

2024-03-17 06:44 UTC, KozlovKV commented on README.md
> -### Configuration files (may be outdated)
А это за что удалил? (

2024-03-17 07:03 UTC, IgorShal commented on README.md
> -### Configuration files (may be outdated)
чтоб не втыкали

2024-03-17 07:08 UTC, IgorShal commented on README.md
> -### Configuration files (may be outdated)
Я не планирую пушить в девелоп пока что

2024-03-17 07:08 UTC, IgorShal commented on README.md
> -### Configuration files (may be outdated)
Скорее просто тест, а дальше уже мб запушим

2024-03-18 04:40 UTC, KozlovKV commented
Для сохранения стабильности надо чётко фиксировать версии, которые мы ставим (не то чтобы это важно в нашем проекте, но в целом это стоит всегда держать в голове).

На Гитхабе у больших репозиториев справа есть вкладка *Releases*, тыкаем на неё и выбираем тжг с нужной версией. Там нужно будет скопировать ссылку на архив (мне больших `zip` нравится), качаем архив, распаковываем и дальше действуем по той же схеме.

Таким образом, для opencv-contrib будут такие команды (для самого opencv в текущем README такие же)
```sh
wget -O opencv-contrib.zip https://github.com/opencv/opencv_contrib/archive/refs/tags/4.8.0.zip
unzip opencv-contrib.zip
```

2024-03-18 09:53 UTC, IgorShal commented
@KozlovKV я назаметно поменял в фичер матчинге radiusMatch на knnMatch и там в функции getGoodMatches есть строчка
```c
		if (allMatches[i][0].distance <  0.7f*allMatches[i][1].distance)
		{
			matches.push_back(allMatches[i][0]);
		}
```
Можешь, пожалуйста, добавить в конфинг параметр чтобы мы могли 0.7f менять

2024-03-18 09:55 UTC, IgorShal commented
Причина:
Так мы получаем более точные матчи + радиус поиска это фулл креп

2024-03-18 14:22 UTC, KozlovKV commented
@AntonTsoy , @IgorShal 

Актульная версия конфига:
```json
{
  "calibrate": false,
  "visualCalibration": true,
  "calibrationPath": "./config/samsung-hp.xml",

  "usePhotosCycle": true,
  "photosPathPattern": "/mnt/c/Users/bakug/YandexDisk/NSU/private/2-1/PAK/static/photos/samsung-tumbochka/*.JPG",
  // "videoSourcePath" has an effect when "usePhotosCycle" is false
  "videoSourcePath": "/mnt/c/Users/bakug/YandexDisk/NSU/private/2-1/PAK/static/samsung-NSU-s.mp4",
  
  "outputDataDir": "./data/video_report/video_test",
  
  "useUndistortion": false,

  "requiredExtractedPointsCount": 1000,
  "featureExtractingThreshold": 15,

  "framesBatchSize": 1,

  "requiredMatchedPointsCount": 200,

  "useFeatureTracker": false,
  // This block has an effect when "useFeatureTracker" is true
  "useOwnFeatureTracker": true,
  "FTThreadsCount": 3,
  "useSADOwnFT": true,
  "useSSDOwnFT": false,
  "FTBarrier": 20,
  "FTMaxAcceptableDifference": 2000,
  
  // This block has an effect when "useFeatureTracker" is false
  "useFM-SIFT-FLANN": true,
  "useFM-SIFT-BF": false,
  "useFM-ORB": false,

  "knnMatcherDistance": 0.7,

  "showTrackedPoints": true,

  // Now this parameters are used only for the first pair of frames
  "RPUseRANSAC": true,
  "RPRANSACProb": 0.999,
  "RPRANSACThreshold": 5.0,
  "RPRequiredGoodPointsPercent": 0.5,
  "RPDistanceThreshold": 200.0
}
```

2024-03-18 14:51 UTC, KozlovKV requested changes
Судя по всему, с Viz у нас всё серьёзно и надолго, так что надо вынести этот код в отдельный модуль (пока что передавай `rotations` отдельно, но учитывая, что потом они будут в `globalDataStruct`)

2024-03-18 14:51 UTC, KozlovKV commented on src/mainCycle.cpp
> +     viz::Viz3d window("Coordinate Frame");
Просто точка начала части с визализацией

2024-03-25 17:24 UTC, IgorShal commented
MVP готов, кода красивый потом добавим.

2024-03-28 11:53 UTC, KozlovKV commented
Вольёшь к себе ветку `merging` либо уже `develop`, поправишь немного стиль - и можно этот PR закрывать. Дальше уже можно добавлять отображение цветов

2024-03-28 11:54 UTC, KozlovKV approved these changes

2024-03-30 12:04 UTC, merged