Best fit batch processing
FIT-2023-SLAM-indoor/slam-indoor-code pull request #50
Opened 2024-03-23 02:45 UTC by KozlovKV

Пока что сделал достаточно приммтивный best fit:
- Впустую пропускаем заданное количество кадров (новый параметр в конфиге)
- Конструируем батч из заданного количества кадров, выбирая тот, в котором фич экстрактится больше заданного количества
- Проходимся по батчу, выбирая кадр с максимальным количеством матчей (также необходимо, чтобы он был больше заданного количества)
- Зачастую получается, что берётся самый первый кадр из батча, хотя так и далеко не всегда

Хотелось бы, чтобы вы проверили эту логику и предложили свои варианты более умного best fit'а (например функция хорошести, которая принимает количество матчей и индекс в кадре, а возвращает число, по которому мы и будем решать, что кадр лучше)

Ещё фан-факт: при обходе батча от конца к началу и от начала к концу получаются разные результаты (выбираются при этом почти одни и те же кадры, но вот результат сильно отличается)

P.S. Сначала я начинал тут допиливать Bundle Adjustment, но с ним не закончил, так что на его файлы внимания не обращайте

2024-03-23 04:19 UTC, KozlovKV commented
Ой, точно, @AntonTsoy , @IgorShal 

Вот конфиг:
```json
{
  "calibrate": false,
  "visualCalibration": true,
  "calibrationPath": "./config/samsung-hv.xml",

  "usePhotosCycle": false,
  "photosPathPattern": "/mnt/c/Users/bakug/YandexDisk/NSU/private/2-1/PAK/static/photos/NSU-hall/*.JPG",
  // "videoSourcePath" has an effect when "usePhotosCycle" is false
  "videoSourcePath": "/mnt/c/Users/bakug/YandexDisk/NSU/private/2-1/PAK/static/samsung-NSU-s.mp4",
  
  "outputDataDir": "./data/video_report/video_test",
  
  "useUndistortion": false,

  "requiredExtractedPointsCount": 200,
  "featureExtractingThreshold": 15,

  "minimalFramesGap": 10,
  "framesBatchSize": 60,

  "requiredMatchedPointsCount": 100,

  "useFeatureTracker": false,
  // This block has an effect when "useFeatureTracker" is true
  "useOwnFeatureTracker": true,
  "FTThreadsCount": 3,
  "useSADOwnFT": true,
  "useSSDOwnFT": false,
  "FTBarrier": 20,
  "FTMaxAcceptableDifference": 2000,
  
  // This block has an effect when "useFeatureTracker" is false
  "useFM-SIFT-FLANN": true,
  "useFM-SIFT-BF": false,
  "useFM-ORB": false,

  "knnMatcherDistance": 0.7,

  "showTrackedPoints": true,

  // Now this parameters are used only for the first pair of frames
  "RPUseRANSAC": true,
  "RPRANSACProb": 0.999,
  "RPRANSACThreshold": 5.0,
  "RPRequiredGoodPointsPercent": 0.5,
  "RPDistanceThreshold": 200.0,

  "useBundleAdjustment": true,
  "BAHuberLossFunctionParameter": 4.0,
  "BAThreadsCnt": 4
}
```

2024-03-23 06:19 UTC, IgorShal commented
Так это ненормально, что у тебя разные результаты при проходе слева направо и наоборот, это может быть только если у тебя несколько максимальных значений, тогда берётся правое, иначе не может быть разных ответов

2024-03-23 06:28 UTC, IgorShal commented
В comma-separated values можно точкой с запятой разделять данные?

2024-03-23 06:34 UTC, IgorShal commented
Мне вообще не нравится идея с начала батча идти, как будто много лишних проверок бесполезных делаем

2024-03-23 06:37 UTC, IgorShal commented
Мне вообще не нравится идея с начала батча идти, как будто много лишних проверок бесполезных делаем . Мы же хотим найти лучший, но самый дальний кадр, поэтому с конца начинать и надо

2024-03-23 06:41 UTC, IgorShal commented
Бестфит идея хорошая, но я всё ещё считаю, что нужно какую-то метрику вводить. Раз почти всегда берётся первый кадр, то это нечем не отличается от обычного ферст фита с размером батча равным минимальному количеству кадров между матчами

2024-03-23 06:54 UTC, IgorShal commented
> Бестфит идея хорошая, но я всё ещё считаю, что нужно какую-то метрику вводить. Раз почти всегда берётся первый кадр, то это ничем не отличается от обычного ферст фита с размером батча равным минимальному количеству кадров между матчами 

Опять же метрика тоже имеет огромный минус:  +  куча  гиперпараметров для перебора. Учитывая, что все они сейчас подбираются вручную + вслепую, я вообще против любого увеличения количества параметров, то есть я в целом против бестфита

2024-03-23 06:56 UTC, IgorShal commented
> > Бестфит идея хорошая, но я всё ещё считаю, что нужно какую-то метрику вводить. Раз почти всегда берётся первый кадр, то это ничем не отличается от обычного ферст фита с размером батча равным минимальному количеству кадров между матчами 
> 
> Опять же метрика тоже имеет огромный минус:  +  куча  гиперпараметров для перебора. Учитывая, что все они сейчас подбираются вручную + вслепую, я вообще против любого увеличения количества параметров, то есть я в целом против бестфита 

Вот бы как-то научиться оценивать математически результаты и сделать автоматический  перебор параметров, но личной я в душе не знаю как

2024-03-23 07:11 UTC, IgorShal commented
> > > Бестфит идея хорошая, но я всё ещё считаю, что нужно какую-то метрику вводить. Раз почти всегда берётся первый кадр, то это ничем не отличается от обычного ферст фита с размером батча равным минимальному количеству кадров между матчами 
> > 
> > Опять же метрика тоже имеет огромный минус:  +  куча  гиперпараметров для перебора. Учитывая, что все они сейчас подбираются вручную + вслепую, я вообще против любого увеличения количества параметров, то есть я в целом против бестфита 
> 
> Вот бы как-то научиться оценивать математически результаты и сделать автоматический  перебор параметров, но личной я в душе не знаю как 

Да и мы уже не успеем

2024-03-23 07:11 UTC, IgorShal commented
> > > > Бестфит идея хорошая, но я всё ещё считаю, что нужно какую-то метрику вводить. Раз почти всегда берётся первый кадр, то это ничем не отличается от обычного ферст фита с размером батча равным минимальному количеству кадров между матчами 
> > > 
> > > Опять же метрика тоже имеет огромный минус:  +  куча  гиперпараметров для перебора. Учитывая, что все они сейчас подбираются вручную + вслепую, я вообще против любого увеличения количества параметров, то есть я в целом против бестфита 
> > 
> > Вот бы как-то научиться оценивать математически результаты и сделать автоматический  перебор параметров, но личной я в душе не знаю как 
> 
> Да и мы уже не успеем

Согласен, Игорь, вот ты всегда всё по фактам говоришь, респект

2024-03-23 07:12 UTC, IgorShal commented
> > > > > Бестфит идея хорошая, но я всё ещё считаю, что нужно какую-то метрику вводить. Раз почти всегда берётся первый кадр, то это ничем не отличается от обычного ферст фита с размером батча равным минимальному количеству кадров между матчами 
> > > > 
> > > > Опять же метрика тоже имеет огромный минус:  +  куча  гиперпараметров для перебора. Учитывая, что все они сейчас подбираются вручную + вслепую, я вообще против любого увеличения количества параметров, то есть я в целом против бестфита 
> > > 
> > > Вот бы как-то научиться оценивать математически результаты и сделать автоматический  перебор параметров, но личной я в душе не знаю как 
> > 
> > Да и мы уже не успеем
> 
> Согласен, Игорь, вот ты всегда всё по фактам говоришь, респект

Спасибо <3

2024-03-24 11:55 UTC, AntonTsoy commented
![image](https://github.com/FIT-2023-SLAM-indoor/slam-indoor-code/assets/112404841/14fbb659-920b-455b-a7fd-7f4bc859cde1)

2024-03-25 17:25 UTC, IgorShal requested changes
Прочитай комменты @KozlovKV

2024-03-26 14:30 UTC, KozlovKV commented
Ввиду кривости метода со скипом кадров перед построением батча (да и самого бэст фита), параметр `"minimalFramesGap"` был уничтожен и БОЛЬШЕ НЕ НУЖЕН (как и сам бэст-фит)

2024-03-26 14:35 UTC, KozlovKV commented
Продолжая сообщение выше. Вернулся на first-fit, но пофиксил при этом критический баг, связанный с тем, что хвост батча после хорошего кадра просто отбрасывался, из-за чего, при проходе далеко от конца батча в одной итерации, на следующей итерации шанс найти хороший кадр для матчинга сильно падал.

Для реализации сохранения хвоста пришлось прокинуть вектор батчей сильно вверх по дереву функций, из-за чего сигнатуры поменялись не только у `fillVideoFrameBatch` и `findGoodVideoFrameFromBatch`, но и у `processingFirstPairFrames` + изменился немного код в `mainCycle` и была добавлена структура `BatchElement`. 

Теперь обработка стала жить несколько дольше + траектория стала приятнее

2024-03-26 17:22 UTC, IgorShal commented
А как так, вроде всё что нужно было, это две строчки добавить, чтобы батч не очищался, откуда поменялись сигнатуры и появилась новая структура 0_0

2024-03-27 02:15 UTC, KozlovKV commented
> А как так, вроде всё что нужно было, это две строчки добавить, чтобы батч не очищался, откуда поменялись сигнатуры, и появилась новая структура 0_0

"ООП (или его подобие) - это не про мало кода" ©️

2024-03-30 12:04 UTC, merged