Colors
FIT-2023-SLAM-indoor/slam-indoor-code pull request #53
Opened 2024-03-30 16:43 UTC by IgorShal

Added colors + some refactoring

2024-03-31 01:33 UTC, AntonTsoy commented on src/vizualizationModule.cpp
>  #include "vizualizationModule.h"
```suggestion

#include "vizualizationModule.h"
```

2024-03-31 01:47 UTC, AntonTsoy requested changes
Все хорошо, осталось только добавить переносы строк между функциями, от этого повысится читаемость

2024-03-31 01:47 UTC, AntonTsoy commented on src/vizualizationModule.cpp
>  #include "vizualizationModule.h"
Также хорошо будет добавить разделение между строками с `using namespace`, глобальной переменной и объявлением функции

2024-03-31 01:51 UTC, AntonTsoy commented on src/vizualizationModule.cpp
>  #include "vizualizationModule.h"
Также хорошо будет добавить разделение между строками с `using namespace`, глобальной переменной и объявлением функции. То же самое с остальной частью файла и хэдером

2024-03-31 06:32 UTC, KozlovKV approved these changes
Ещё из рефакторных моментов: перенеси файлы визуализатора в отдельную папку

2024-04-02 05:00 UTC, KozlovKV requested changes

2024-04-02 05:00 UTC, KozlovKV commented on src/vizualizationModule.cpp
> +    std::vector<Mat> rotations,
Если для копирования нет какого-то особого резона, то лучше везде использовать ссылки `&`

2024-04-02 05:00 UTC, KozlovKV commented on src/vizualizationModule.cpp
>      window.spin();
В некоторых случаях падает с таким выводом на этой строке:
```
Video is over. No more frames...
[1, 1]
[1, 1]
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  64 (X_PolyPoint)
  Value in failed request:  0x3
  Serial number of failed request:  68
  Current serial number in output stream:  69
Signal: SIGSEGV (Segmentation fault)
```
Причём на одних и тех же данных может как работать, так и нет. Самый неприятный тип ошибок. В теории, то, что написал в этом ревью выше, может помочь, но уверенности никакой...

2024-04-02 09:34 UTC, IgorShal commented on src/vizualizationModule.cpp
>      window.spin();
Искренне без понятия, что за хрень

2024-04-02 09:39 UTC, IgorShal commented
@KozlovKV попробуй так

2024-04-04 09:54 UTC, merged