Restart cycle
FIT-2023-SLAM-indoor/slam-indoor-code pull request #55
Opened 2024-04-02 16:10 UTC by AntonTsoy

Ой...
Не смотрите, не надо этого вам...

2024-04-04 10:44 UTC, KozlovKV requested changes
Очень неплохо. Не считая нормального возврата при обработке первых двух кадров, изменения нужны совсем небольшие

2024-04-04 10:44 UTC, KozlovKV commented on src/cycleProcessing/mainCycleInternals.h
> +void insertNewGlobalData(GlobalData mainGlobalData, GlobalData newGlobalData);
Надо бы по ссылкам это делать. По идее, так это работать не будет

2024-04-04 10:44 UTC, KozlovKV commented on src/cycleProcessing/mainCycleInternals.cpp
> +void insertNewGlobalData(GlobalData mainGlobalData, GlobalData newGlobalData) {
См. коммент выше

2024-04-04 10:44 UTC, KozlovKV commented on src/cycleProcessing/mainCycleInternals.cpp
> + * @param [in] matchIdx ABOBA!
[AMOGUS](https://www.youtube.com/watch?v=xSeXZRJOX54)

2024-04-04 10:44 UTC, KozlovKV commented on src/cycleProcessing/mainCycle.cpp
> +			return EMPTY_BATCH;
В этот момент в векторе `processedFramesData` уже могли накопиться данные, которые надо перегнать в глобал дату, так что делать `return` нельзя - вместо этого создай переменную результата перед циклом, записывай в неё значения и брэйкайся. В конце можно будет возвращать значение этой переменной

Ну либо какой-нибудь другой вариант, чтобы `if (!processedFramesData.empty())` срабатывал

2024-04-04 10:44 UTC, KozlovKV commented on src/cycleProcessing/mainCycle.cpp
> +            return lastFrameIdx;
См. коммент выше

2024-04-04 10:44 UTC, KozlovKV commented on src/cycleProcessing/mainCycle.cpp
> -            lastFrameIdx++;
Если убирать `return`ы из цикла, то перед инкрементацией надо это значение также в переменную возврата сохранять

2024-04-04 10:44 UTC, KozlovKV commented on src/cycleProcessing/mainCycle.cpp
>          exit(-1);
Возможно это был не первый запуск главного цикла, так что умирать мы не очень хотим, а вот заключить, что дальше видео совсем плохое - вполне нормальный вариант, так что вот тут уже можно делать `return` с каким-нибудь особым кодом возврата

А ещё видео могло просто кончиться

2024-04-04 10:44 UTC, KozlovKV commented on src/cycleProcessing/mainCycle.cpp
>  static bool processingFirstPairFrames(
Получается, тут тоже надо что-то похитрее булевой переменной возвращать

2024-04-04 10:44 UTC, KozlovKV commented on src/cycleProcessing/mainCycle.cpp
> +		int frameIndex = findGoodFrameFromBatch(
Здесь `frameIndex` пересоздаётся, а это скорее всего не то, что нам надо

2024-04-04 10:58 UTC, AntonTsoy commented on src/cycleProcessing/mainCycle.cpp
> +		int frameIndex = findGoodFrameFromBatch(
писать код в 2 часа ночи вредно

2024-04-04 11:26 UTC, KozlovKV commented on src/cycleProcessing/mainCycle.cpp
> +		int frameIndex = findGoodFrameFromBatch(
🥲

2024-04-07 12:37 UTC, KozlovKV approved these changes

2024-04-07 12:37 UTC, KozlovKV commented on src/cycleProcessing/mainCycle.cpp
> +}
CMake ругается на эту строчку warning-ом, потому что тут у нас ничего не возвращается из функции, где должен возвращаться инт, но по факту мы этого места не достигнем никогда, так что норм

2024-04-07 13:52 UTC, IgorShal approved these changes

2024-04-07 14:38 UTC, merged