Clusterization
FIT-2023-SLAM-indoor/slam-indoor-code pull request #65
Opened 2024-05-25 16:03 UTC by IgorShal

Ультра сыро

2024-05-26 05:02 UTC, IgorShal commented
```c
  //Max summary distance(color*colorWeight + distance*euclidWeight) between points to connect them by edge
  "TriangleMaxDistance": 6.0,
  //Euclide distance weight (euclidWeight in formula above)
  "TriangleEuclidDistanceWeight": 5.0,
  //same for color
  "TriangleColorDistance": 1.4,
  //minimum points in triangulation to show it
  "TriangleMinimumPoints": 10
```

2024-05-26 05:02 UTC, IgorShal commented
Новые поля конфига

2024-05-26 05:12 UTC, KozlovKV approved these changes

2024-05-26 05:12 UTC, KozlovKV commented on src/vizualization/delauney-triangulation/geomAdditionalFunc.cpp
> +    #pragma omp parallel for schedule(dynamic) num_threads(10)
А мы можем в директиве препроцессора ставить переменные? Было бы классно и значение потоков вынести в конфиг. Хотя... Не уверен, что здесь в этом есть такая большая нужда

2024-05-26 09:15 UTC, KozlovKV requested changes

2024-05-26 09:15 UTC, KozlovKV commented on src/config/configData.h
>  };
Добавишь булевое поле для включения/отключения треугольников?

2024-05-27 12:26 UTC, KozlovKV approved these changes

2024-05-28 12:35 UTC, merged